### ISSUE TITLE
Collect data - women in tech

### ISSUE THREAD

**Issue by phloreenm** [phloreenm/team4-march-hackathon#4]

**Comment by kpetrauskas92** [comment]
My Research on "Nikki Durkin" Life events

    1. Nikki Durkin was born on December 19, 1991, in Australia.
    2. In 2011, Durkin founded 99dresses, an online marketplace for trading clothing with virtual currency.
    3. In 2013, 99dresses shut down due to financial difficulties.
    4. In 2014, Durkin founded Codemakers, a company that provided coding education and resources for children.
    5. In 2017, Codemakers was acquired by the Australian edtech company, 3P Learning.
    6. Currently, Durkin is the founder and CEO of Parity, a startup that aims to help companies support gender equality in the workplace.

![Image](https://user-images.githubusercontent.com/118168899/225749976-04a91e62-0da5-413c-acb9-447d8c8d3d0e.jpg)

[Source](https://content.api.news/v3/images/bin/d9c2366d32be8995340bde1f9de32229)

About text -

Nikki Durkin is an Australian entrepreneur who has made a significant impact in the tech industry through her innovative startups. She was born on December 19, 1991, and grew up in Sydney, where she attended the University of New South Wales, studying commerce and law.

Durkin's entrepreneurial journey began in 2011 when she founded 99dresses, an online marketplace for trading clothing with virtual currency. Although the startup faced financial difficulties and eventually shut down in 2013, it was a testament to Durkin's ambition and innovation in the industry.

Following the closure of 99dresses, Durkin founded Codemakers in 2014, which provided coding education and resources for children. Her goal was to teach children how to code and equip them with the necessary tools to become future leaders in the technology industry. Codemakers was later acquired by 3P Learning, an Australian edtech company, in 2017.

Currently, Durkin is the founder and CEO of Parity, a startup that aims to help companies support gender equality in the workplace. The platform offers a range of benefits that address gender gaps and support women in the workplace.

Durkin's entrepreneurial journey has been marked by her passion for technology and her commitment to making a difference. She has demonstrated that through hard work, determination, and innovation, anyone can create meaningful change in the world of tech.


Let me know if this will be ok @emmahewson
