### ISSUE TITLE
Source homepage hero image

### ISSUE THREAD

**Issue by quiltingcode** [phloreenm/team4-march-hackathon#50]

**Comment by kpetrauskas92** [comment]
Few ideas.

https://www.pexels.com/photo/woman-in-white-shirt-playing-chess-against-a-robot-8438951/
https://www.pexels.com/photo/people-on-conference-room-1181427/

Lots more on Pexels. @quiltingcode

**Comment by kpetrauskas92** [comment]
Sourced
