### ISSUE TITLE
Write homepage intro paragraph

### ISSUE THREAD

**Issue by quiltingcode** [phloreenm/team4-march-hackathon#51]

**Comment by phloreenm** [comment]
version: 
"Welcome to our page dedicated to celebrating and promoting the achievements of women in technology and sciences. Throughout history, many women have made significant contributions to these fields, yet their stories often go untold. From researchers like Chien Shiung Wu, astronomers like Maria Mitchell, and computer scientists like Grace Hopper, these women have paved the way for future generations. Join us as we explore some of these amazing stories and work towards a more inclusive future in technology and sciences."

**Comment by kpetrauskas92** [comment]
Welcome to our website dedicated to empowering women in tech and tackling the issue of lack of representation in the industry. We understand that women face unique challenges and barriers in the tech field, and we are committed to creating a community that supports and celebrates women in all stages of their tech careers.

Our website features some of the most influential and inspiring women in tech, who have broken through the glass ceiling and paved the way for future generations. From engineers to entrepreneurs, our role models come from diverse backgrounds and have achieved remarkable success in their fields.

In addition to featuring inspiring women in tech, our website also offers a quiz to help you find your perfect role model. By answering a few simple questions, you can discover a role model who shares your interests, experiences, and career goals. This can help you connect with like-minded women in tech and gain valuable insights into how to achieve success in your own career.

We believe that by creating a strong community of women in tech and sharing the stories and experiences of successful women, we can break down barriers and create a more diverse and inclusive industry. We invite you to join us on this journey and be a part of the movement to empower women in tech.
